# Generated by Django 3.2 on 2024-08-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20240803_1823'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='Unique review constraint',
        ),
    ]
