# Generated by Django 3.2 on 2024-08-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_unique review constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
